version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.aleksturbo.website`)"
    networks:
      - bashdays

networks:
  bashdays:
    external: true